### ISSUE TITLE
Define GRG by Reference System by Area widget tool does not create a "complete grid"

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-grg-widget#106]
### Widget

When a create GRG based on reference system by area the tool doesn't always create a complete grid i.e. it didn't create all the grid cells that intersect the extent that I drew (in this case I was trying to create a 10,000 meter grid):

![image](https://user-images.githubusercontent.com/4635490/30877450-9f112644-a2ae-11e7-9b1e-da129839d9f2.png)
NOTE: it also creates extra grids squares. If I can to choose between the two, I'd rather have extra grid squares, then less.
This was in Canada, west of Lake Winnipeg.

**Comment by joebayles** [comment]
I think this is a known issue, suggest adding the documentation tag.

**Comment by adgiles** [comment]
This issue was addressed as much as possible a while ago, it only happens occasionally when working across a grid zone change. When a 'complete gird' is not created the user can click back and adjust the size of grid extent box to add / remove grid cells they do not want. Once the grid is created you can also right click an individual grid cell and remove it as required.

**Comment by topowright** [comment]
This is a known issue that we really do not have a way forward at this time.
