### ISSUE TITLE
Clip Grid to GRG Area toggle options are reversed

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-grg-widget#145]
Issue reported by @MikeTschudi 

### Bug or Enhancement
The Clip Grid to GRG Area toggle positions for "on" and "off" are reversed in the UI.

### Repo Steps or Enhancement details
1. Open GRG widget
2. Select Define a Grid from an Area
3. Select By Reference System
4. Note the Clip Grid to GRG Area toggle button.

The user slides the toggle right (red) to disable the option to clip grid to GRG area and slides it left (green) to enable the option to clip grid to GRG area. 

### Screenshots
![image](https://user-images.githubusercontent.com/3800729/35174972-5f9f531e-fd26-11e7-9be5-f36f7e86a65b.png)
![image](https://user-images.githubusercontent.com/3800729/35174980-633914e2-fd26-11e7-997b-bcdb0b31bcb3.png)

The standard for iOS-style toggles is slide right to get it on/enable/green and left to get it off/disable/red.
![image](https://user-images.githubusercontent.com/3800729/35173998-8a4f2e6c-fd22-11e7-9edb-b9ee86236a54.png)
 
Version found:
GRG January 2018
WAB 2.7

**Comment by adgiles** [comment]
This is the same toggle that is used across all widgets within Web AppBuilder

**Comment by lfunkhouser** [comment]
@MikeTschudi I agree with you that it is confusing since UI guidelines for toggles are on/right and off/left. Do you have examples of specific widgets that follow this design? 

We followed the pattern of other widgets and are consistent with widgets like the "Add Data" widget, for example:
![image](https://user-images.githubusercontent.com/3800729/35178336-89f2aa60-fd3c-11e7-9e7f-2bd382dd9b15.png)
![image](https://user-images.githubusercontent.com/3800729/35178338-8d4d98c8-fd3c-11e7-83c8-7a1bd4696587.png)

**Comment by MikeTschudi** [comment]
I found the toggle in AddData & GridOverlay, and as @adgiles pointed out, their behavior is the same as GRG. 

@Jianxia, this toggle seems confusing in AddData & GridOverlay as well. With GridOverlay, it's not so bad because one can just re-open the widget and change the toggle, but for AddData, it's a lot less clear.

**AddData**:
![image](https://user-images.githubusercontent.com/2125181/35184349-34f7a67e-fda9-11e7-950b-8e21cb8c68ea.png)
![image](https://user-images.githubusercontent.com/2125181/35184350-3a62ef6a-fda9-11e7-9bc6-222e0bc99978.png)

**GridOverlay** off state (i.e., grid is not displayed when widget is closed):
![image](https://user-images.githubusercontent.com/2125181/35184378-ad321a34-fda9-11e7-8cf9-eda7276efb12.png)

**Comment by MikeTschudi** [comment]
@lfunkhouser, I only did a cursory check of a dozen widgets, but didn't find additional slide toggles; checkboxes are more common.

While the slide toggle usage is clearly consistent within WAB, we are adding friction to the UI by bucking long-held convention outside of the WAB.

In addition to the iOS example above,

[Dojo](https://dojotoolkit.org/reference-guide/1.10/dojox/mobile/Switch.html)
![image](https://user-images.githubusercontent.com/2125181/35185532-e05c0ff8-fdba-11e7-8e9c-d6957bfdffeb.png)
![image](https://user-images.githubusercontent.com/2125181/35185541-fd97ebbe-fdba-11e7-8650-b80ceab88341.png)

[Android](https://developer.android.com/guide/topics/ui/controls/togglebutton.html)
![image](https://user-images.githubusercontent.com/2125181/35184500-674c14dc-fdab-11e7-8858-23381289af38.png)

[Windows](https://docs.microsoft.com/en-us/windows/uwp/design/controls-and-patterns/toggles)
![image](https://user-images.githubusercontent.com/2125181/35184517-96bc3df0-fdab-11e7-9e80-b14abd16a549.png)
![image](https://user-images.githubusercontent.com/2125181/35184526-a5abfa8a-fdab-11e7-9aec-23a679831fed.png)
([MacOS](https://developer.apple.com/macos/human-interface-guidelines/buttons/push-buttons/), on the other hand seems to have moved to checkboxes: "Use a checkbox instead of a button when the user needs to choose between two states. The on and off states of a checkbox are generally clearer to most users than a push button that's configured as a toggle.")

[QML](http://doc.qt.io/qt-5/qml-qtquick-controls-switch.html)
![image](https://user-images.githubusercontent.com/2125181/35185422-20ae0c34-fdb9-11e7-8bf2-7e4a5f2907bb.png)

**Comment by adgiles** [comment]
Addressed in PR https://github.com/Esri/solutions-grg-widget/pull/155. 

No documentation change required. Just needs to be verified and moved up to devtopia

**Comment by topowright** [comment]
This has been verified and  pushed into devtopia
