### ISSUE TITLE
No warning is given when GRG cannot publish a grid because it does not have proper org credentials

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-grg-widget#172]
### Bug or Enhancement
No warning is given when GRG cannot publish a grid because it does not have proper org credentials
### Repo Steps or Enhancement details
1. Create a grid
2. Name the grid and click publish
3. Enter credentials for an account that does not have access to the org account used to register the portal.  I registered the app with arcgisfordefense.maps.arcgis.com so I used an arcgis.com account i set up just for testing.
4. Click OK.

No error is given that it cannot publish the grid. No confirmation is given like you would get if it were published.  No layer is published in the arcgis.com account for which you entered credentials.

**Comment by dfoll** [comment]
@adgiles

**Comment by dfoll** [comment]
another instance I found of publishing failing with no error message is if the credentials entered are for an account that only had viewer permissions.

**Comment by adgiles** [comment]
@dfoll. The code was not handling any errors being returned due to incorrect credentials or user permissions. I have addressed these in this PR:   

Recreating steps above:

1. Create a grid.
2. Name the grid and click publish.
3. Enter credentials for an account that does not have access to the org account used to register the portal.  I registered the app with arcgisfordefense.maps.arcgis.com so I used an arcgis.com account i set up just for testing.

**I have used my online developer account credentials:**

![capture](https://user-images.githubusercontent.com/3740334/36199443-842d8976-1171-11e8-867e-12f6a28ad40e.PNG)

4. Click OK.

**You are now informed you do not have access:**

![capture](https://user-images.githubusercontent.com/3740334/36199477-9fdac832-1171-11e8-9980-481e3a8ff360.PNG)

**Comment by adgiles** [comment]
Check list tests need updating to test different accounts:

- Valid accounts that are not part of the org
- Valid accounts that are in the org but are only viewers

 that are not part of the org and

**Comment by dfoll** [comment]
updated checklist test to include steps to test for":
 - valid org user with proper permissions
 - valid org user without proper permissions
 - not valid org user

**Comment by dfoll** [comment]
tested and verified. The bug has been resolved, but I believe there is still a little more to do with the workflow and messaging. I am closing this issue and have opened
