### ISSUE TITLE
Create GRG from last known position using speed and elapsed timeframe to set extent

### ISSUE THREAD

**Issue by nfeuerstein** [Esri/solutions-grg-widget#27]
Select origin and then type in last known speed and time at location to create grid extent

**Comment by topowright** [comment]
Today I was able to speak with @nfeuerstein and with Phil Suarez about this workflow. The feedback from both  was that it has a place in the tool. @nfeuerstein provided the thought that it should just be another way to derive a GRG from point. Instead of having a set amount of grid boxes that would be created it would be based off of time and distance of travel from the given start point. 

Here would be where we would add the access to this capability: 
![image](https://user-images.githubusercontent.com/5488313/34546554-779f525e-f0a9-11e7-95b9-b25ccc33ab2a.png)

**Comment by topowright** [comment]
The second UI where the user interacts with the tool will look like this: 
![image](https://user-images.githubusercontent.com/5488313/34546749-e2ab6852-f0aa-11e7-9a49-37016215b157.png)
@ACueva and @dfoll  does this okay for you guys?

**Comment by adgiles** [comment]
I think the time and rate UI layout and select options should be the same as we have used in D&D:

![untitled](https://user-images.githubusercontent.com/3740334/34560104-7fc0cd12-f13c-11e7-914d-b68d2727a151.png)
![untitled1](https://user-images.githubusercontent.com/3740334/34560108-82380574-f13c-11e7-9b06-064d34eeeac4.png)

**Comment by adgiles** [comment]
Status as at 16:45 4 Jan 18

UI changes complete, around 70% complete on the code logic, will hopefully complete by COP 5 Jan 18

**Comment by adgiles** [comment]
Initial dev work in this PR https://github.com/Esri/solutions-grg-widget/pull/128

**Comment by topowright** [comment]
@dfoll @ACueva  I think this is ready for review and documentation. 
@kgonzago has merged the code and now we need to verify the work that is done.

**Comment by dfoll** [comment]
@lfunkhouser @topowright @adgiles in the context of the "GRG from Point using Time and Speed" menu what does the (DD) after GRG Origin mean?

**Comment by dfoll** [comment]
- [ ] Added workflow to "Create GRG from a point using the widget" topic in cms (removed G-Doc (CMS))
- [ ] I believe Doc (solution) does not apply
- [ ] Added notes to https://github.com/ArcGIS/solutions-defense/issues/536 for when GRG is released, to update the "what is new" for defense, the "release notes" page in cms, and "release notes on home page" (removed G-Doc (website))
